#!/bin/sh

repo_git() {
  if [ -x /Library/Developer/CommandLineTools/usr/bin/git ]; then
    /Library/Developer/CommandLineTools/usr/bin/git "$@"
  else
    git "$@"
  fi
}

branch=$(repo_git branch --show-current)

if [ "$branch" = "main" ]; then
  repo_git push origin "$branch"
fi
